### ISSUE TITLE
ssh bc4-external invalid

### ISSUE THREAD

**Issue by JoelGG** [COMSM0018-Applied-Deep-Learning/labsheets#3]
I have set up seis, which verified that I have the correct password for my account. This doesn't work for bc4-external, where I'm getting a validation error when trying to enter my password. I'm not sure how to rectify this.

Best,
Joel

**Comment by DWhettam** [comment]
Have you registered an account with BC4? Details on the bottom of the [course webpage](https://comsm0045-applied-deep-learning.github.io/)
